name: deploy-network
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Execute deploy script
        run: |
          bash scripts/deploy-network.sh --resource-group NetworkWatcherRG --location mexicocentral
